---
BARMAN_CLIENT_POSTGRESQL_VERSION: "9.6"
BARMAN_CLINET_LISTEN_ADDRESSES: "*"
BARMAN_CLIENT_POSTGRESQL_MAX_WAL_SENDERS: "8"
BARMAN_CLIENT_POSTGRESQL_MAX_REPL_SLOTS: "8"
BARMAN_CLIENT_POSTGRESQL_USER: "barman"
BARMAN_CLIENT_POSTGRESQL_USER_PASSWORD: "barman"
BARMAN_CLIENT_IP_OF_BACKUP_SERVER: "10.15.58.232"