---
- name: Barman client | Install Postgresql server
  apt:
    name: "postgresql-{{ BARMAN_CLIENT_POSTGRESQL_VERSION }}"

- name: Barman client | Install Postgresql server tools
  apt:
    name: "{{ item }}"
    state: "present"
  loop: 
    - postgresql-server-dev-9.6
    - python-pip

- name: Barman client | Install Postgresql server tools
  pip:
    name: "psycopg2"

- name:  Barman client | WAL LEVEL
  lineinfile: 
    dest: "/etc/postgresql/{{BARMAN_CLIENT_POSTGRESQL_VERSION}}/main/postgresql.conf"
    regexp: "^#wal_level|^wal_level"
    insertbefore: "BOF"
    line: "wal_level = hot_standby"

- name:  Barman client | MAX_WAL_SENDERS
  lineinfile: 
    dest: "/etc/postgresql/{{BARMAN_CLIENT_POSTGRESQL_VERSION}}/main/postgresql.conf"
    regexp: "^#max_wal_senders|^max_wal_senders"
    insertbefore: "BOF"
    line: "max_wal_senders = {{ BARMAN_CLIENT_POSTGRESQL_MAX_WAL_SENDERS }}"

- name:  Barman client | LISTEN_ADDRESSES
  lineinfile: 
    dest: "/etc/postgresql/{{BARMAN_CLIENT_POSTGRESQL_VERSION}}/main/postgresql.conf"
    regexp: "^#listen_addresses|^listen_addresses"
    insertbefore: "BOF"
    line: "listen_addresses = '{{ BARMAN_CLINET_LISTEN_ADDRESSES}}'"

- name:  Barman client | max_replication_slots enable
  lineinfile:
    dest: "/etc/postgresql/{{BARMAN_CLIENT_POSTGRESQL_VERSION}}/main/postgresql.conf"
    regexp: "^#max_replication_slots|^max_replication_slots"
    insertbefore: "BOF"
    line: "max_replication_slots = {{BARMAN_CLIENT_POSTGRESQL_MAX_REPL_SLOTS}}"

- name: Barman client | Add comment to pg_hba
  lineinfile: 
    dest: "/etc/postgresql/{{BARMAN_CLIENT_POSTGRESQL_VERSION}}/main/pg_hba.conf"
    insertafter: "EOF"
    regexp: "# Allow replication connections from backup server"
    line: "# Allow replication connections from backup server"

- name: Barman client | Add authorization rule for replication for user
  lineinfile:
    dest: "/etc/postgresql/{{BARMAN_CLIENT_POSTGRESQL_VERSION}}/main/pg_hba.conf"
    insertafter: "EOF"
    line: "host replication {{BARMAN_CLIENT_POSTGRESQL_USER}} {{BARMAN_CLIENT_IP_OF_BACKUP_SERVER}}/32 md5"

- name: Barman client | Add authorization rule for connections for user
  lineinfile:
    dest: "/etc/postgresql/{{BARMAN_CLIENT_POSTGRESQL_VERSION}}/main/pg_hba.conf"
    insertafter: "EOF"
    line: "host all {{BARMAN_CLIENT_POSTGRESQL_USER}} {{BARMAN_CLIENT_IP_OF_BACKUP_SERVER}}/32 md5"
  register: changes_of_authenthication_file

- name: Barman client | Create postgresql replication user and add grants
  become_user: postgres
  postgresql_user:
    name: "{{BARMAN_CLIENT_POSTGRESQL_USER}}"
    password: "{{BARMAN_CLIENT_POSTGRESQL_USER_PASSWORD}}"
    role_attr_flags: "SUPERUSER"

- name: Barman client | Restarting PostgreSQL
  systemd:
    state: reloaded
    name: postgresql
  when: changes_of_authenthication_file.changed == true

- name: Barman client | Get the package facts
  package_facts:
    manager: "auto"

- name: Barman client | Add Ferm rule for postgresql
  template:
   src: "templates/etc/ferm/filter-input.d/35_allow_postgresql_port_for_barman.conf.j2"
   dest: "/etc/ferm/filter-input.d/35_allow_postgresql_port_for_barman.conf"
   owner: "root"
   group: "root"
   mode: "0644"
  when: ansible_facts.packages.ferm is defined

- name: Barman client | Allow 5432 port for connections
  iptables:
    chain: INPUT
    source: '{{BARMAN_CLIENT_IP_OF_BACKUP_SERVER}}/32'
    jump: ACCEPT
    protocol: tcp
    destination_port: "5432"
    comment: /* allow postgresql for barman */
  when: ansible_facts.packages.ferm is not defined

