---

#### Notification: you need to deploy barman-client role first! ####

- name: Config barman client
  hosts: barman_client
  become: "yes"
  gather_facts: "yes"
  roles:
    - role: "barman-client"
      BARMAN_CLIENT_POSTGRESQL_VERSION: "9.6"
      BARMAN_CLINET_LISTEN_ADDRESSES: "*"
      BARMAN_CLIENT_POSTGRESQL_MAX_WAL_SENDERS: "8"
      BARMAN_CLIENT_POSTGRESQL_MAX_REPL_SLOTS: "8"
      BARMAN_CLIENT_POSTGRESQL_USER: "barman"
      BARMAN_CLIENT_POSTGRESQL_USER_PASSWORD: "barman"
      BARMAN_CLIENT_IP_OF_BACKUP_SERVER: "127.0.0.1"
  tags: client

- name: config barman server
  hosts: barman_server
  become: "yes"
  gather_facts: "yes"
  roles: 
    - role: "barman-server"
      BARMAN_SERVER_HOME_DIR: "/var/lib/barman"
      BARMAN_SERVER_DB_CONF_FILE_NAME: "postgres"
      BARMAN_SERVER_DB_CONF_FILE_DESCRIPTION: "your description"
      BARMAN_SERVER_DB_CONN_INFO_HOST: "127.0.0.1"
      BARMAN_SERVER_DB_CONN_INFO_USER: "barman"
      BARMAN_SERVER_DB_CONN_INFO_USER_PASSWORD: "barman"
      BARMAN_SERVER_DB_NAME: "postgres"
      BARMAN_SERVER_DB_SLOT_NAME: "barman"
      BARMAN_SERVER_RETENTION_POLICY: "RECOVERY WINDOW OF 7 DAYS"
      BARMAN_SERVER_LAST_BACKUP_MAXIMUM_AGE: "1 DAYS"
  tags: server
